@token=fYORx5uRpBPyObqU84DyOkHtDIheBB2fyARsOJ5Veqo=

# Create a new label
POST http://localhost:8080/labels HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "name": "Label 1",
  "color": "#00000"
}

###

# Get all labels
GET http://localhost:8080/labels HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

# Get a label
GET http://localhost:8080/labels/11 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

# Delete a label
DELETE http://localhost:8080/labels/3 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

# Update a label
PUT http://localhost:8080/labels/7 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "name": ""
}
