### Create a new label
POST http://localhost:8080/labels HTTP/1.1
Authorization: Bearer BVKnzIdWy_0VeM_MNigo4L3Ii2JXjGlyEW8q3tL-ZXM=
Content-Type: application/json

{
    "user_id": 1,
    "name": "test2",
    "color": "#000000"
}


### Get all labels
GET http://localhost:8080/labels HTTP/1.1
Authorization: Bearer BVKnzIdWy_0VeM_MNigo4L3Ii2JXjGlyEW8q3tL-ZXM=
Accept: application/json


### Get a label
GET http://localhost:8080/labels/10 HTTP/1.1
Authorization: Bearer BVKnzIdWy_0VeM_MNigo4L3Ii2JXjGlyEW8q3tL-ZXM=
Accept: application/json


### Delete a label
DELETE http://localhost:8080/labels/10 HTTP/1.1
Authorization: Bearer BVKnzIdWy_0VeM_MNigo4L3Ii2JXjGlyEW8q3tL-ZXM=
Accept: application/json

### Update a label
PUT http://localhost:8080/labels/11 HTTP/1.1
Authorization: Bearer BVKnzIdWy_0VeM_MNigo4L3Ii2JXjGlyEW8q3tL-ZXM=
Accept: application/json

{
    "name": "test7"
}
