@token="Bearer fYORx5uRpBPyObqU84DyOkHtDIheBB2fyARsOJ5Veqo="

# Create a new project
POST http://localhost:8080/projects HTTP/1.1
authorization: {{token}}
content-type: application/json
accept: application/json

{
  "content": "test",
  "description": "test"
}

###

# Get a project
GET http://localhost:8080/projects/22 HTTP/1.1
authorization: {{token}}
accept: application/json

###

# Get all projects
GET http://localhost:8080/projects HTTP/1.1
authorization: {{token}}
accept: application/json

###

# Update a project
PUT http://localhost:8080/projects/28 HTTP/1.1
authorization: {{token}}
content-type: application/json
accept: application/json

{
  "content": "test1",
  "description": "tes1t"
}

###

# Reorder projects
# Archive a project
PUT http://localhost:8080/projects/23/archive HTTP/1.1
authorization: {{token}}
content-type: application/json
accept: application/json
authorization: {{token}}
accept: application/json

{
  "parent_id": null,
  "children": [
    { "id": 28, "child_order": 0 },
    { "id": 29, "child_order": 1 },
    { "id": 30, "child_order": 2 }
  ]
}

###

# Unarchive a project
PUT http://localhost:8080/projects/22/unarchive HTTP/1.1
authorization: {{token}}
accept: application/json

###

# Delete a label
DELETE http://localhost:8080/projects/27 HTTP/1.1
authorization: {{token}}
accept: application/json
