@token=fYORx5uRpBPyObqU84DyOkHtDIheBB2fyARsOJ5Veqo=

# Create a new project
POST http://localhost:8080/projects HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "content": "test2",
  "description": "test1"
}

###

# Get a project
GET http://localhost:8080/projects/22 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

# Get all projects
GET http://localhost:8080/projects HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

# Update a project
PUT http://localhost:8080/projects/43 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "description": "test1"
}

###

# Reorder projects
PUT http://localhost:8080/projects/reorder HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
Accept: application/json

{
  "parent_id": null,
  "children": [
    { "id": 45, "child_order": 0 },
    { "id": 46, "child_order": 1 }
  ]
}

###

# Archive a project
PUT http://localhost:8080/projects/43/archive HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

# Unarchive a project
PUT http://localhost:8080/projects/43/unarchive HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

###

# Delete a label
DELETE http://localhost:8080/projects/43 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json
