@token="Bearer fYORx5uRpBPyObqU84DyOkHtDIheBB2fyARsOJ5Veqo="

# Create a new task
POST http://localhost:8080/tasks HTTP/1.1
authorization: {{token}}
content-type: application/json
accept: application/json

{
  "content": "test",
  "description": "test",
  "due": {
    "date": "2024-07-20T00:00:00Z",
    "recurring": false
  },
  "duration": {
    "amount": 10,
    "unit": "minute"
  },
  "labels": ["test"],
  "priority": 1
}

###

# Get all tasks
GET http://localhost:8080/tasks HTTP/1.1
authorization: {{token}}
accept: application/json

###

GET http://localhost:8080/tasks/17 HTTP/1.1
authorization: {{token}}
accept: application/json

###

# Delete a task
DELETE http://localhost:8080/tasks/21 HTTP/1.1
authorization: {{token}}
