@token="Bearer fYORx5uRpBPyObqU84DyOkHtDIheBB2fyARsOJ5Veqo="

# Create a new token
POST http://localhost:8080/token HTTP/1.1
accept: application/json
content-type: application/json

{
  "user_id": 26,
  "password": "test123456"
}

###

# Get tokens
GET http://localhost:8080/tokens HTTP/1.1
accept: application/json
authorization: {{token}}

###

# Update a tokens
PUT http://localhost:8080/tokens/10 HTTP/1.1
authorization: {{token}}
accept: application/json

{
  "user_id": 21,
  "password": "test123456"
}

###

# Delete a label
DELETE http://localhost:8080/tokens/8 HTTP/1.1
authorization: {{token}}
accept: application/json
