@token=fYORx5uRpBPyObqU84DyOkHtDIheBB2fyARsOJ5Veqo=

# Create a new user
POST http://localhost:8080/registry HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "username": "test",
  "password": "test123456",
  "email": "test@test.com"
}

###

# Get the user
GET http://localhost:8080/users/26 HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}

###

# Update the user
PUT http://localhost:8080/users/21 HTTP/1.1
Accept: application/json
Authorization: {{token}}
Content-Type: application/json

{
  "username": "yufe",
  "old_password": "test123456",
  "email": "test@test.com"
}

###

# Delete the user
DELETE http://localhost:8080/users/25 HTTP/1.1
Authorization: {{token}}
